### ISSUE TITLE
AttributeError: module 'func_vpr' has no attribute 'loadDINONV'

### ISSUE THREAD

**Issue by xxx-sr** [AnyLoc/Revisit-Anything#5] opened 2024-11-13 11:23 UTC
Hi oravus,

I encountered an issue with the func_vpr module. When I try to call the loadDINONV function, I get the following error:

Traceback (most recent call last):
  File "place_rec_DINO_finetuned.py", line 91, in <module>
    backbone = func_vpr.loadDINONV(cfg_dino, dino_nv_checkpoint, device="cuda", feat_type="backbone")
AttributeError: module 'func_vpr' has no attribute 'loadDINONV'

Could you kindly help me understand if this function is missing, deprecated, or if there's another way to load the DINO model in this case?

Thanks in advance for your help!

Best regards,
xxx

**Comment by Kartikgar** [comment] 2024-11-28 07:50
Hi @xxx-sr,
We apologize for the delay. The code is fixed now and will run as intended. Let us know if you face any issues.

**Closed as completed** 2024-12-05 04:34 UTC
